[project]
name = "pid-component"
version = "0.3.0"
description = "Monorepo for the PID Component and related packages"
license = "Apache-2.0"
repository = "https://github.com/kit-data-manager/pid-component"
homepage = "https://kit-data-manager.github.io/pid-component"
documentation = "https://kit-data-manager.github.io/pid-component"
keywords = [
  "react",
  "pid",
  "datatyperegistry",
  "handle.net",
  "orcid",
  "identifier",
  "kit-data-manager",
  "typescript",
  "storybook",
  "tailwindcss",
  "fair",
  "fairdata",
  "fairdo",
  "fairdigitalobject"
]

[[project.people]]
given-names = "Christopher"
family-names = "Raquet"
email = "christopher.raquet@kit.edu"
orcid = "https://orcid.org/0009-0003-2196-9187"
affiliation = "Karlsruhe Institute of Technology (KIT)"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = true  # currently maintains the project (i.e. is a contact person)

[[project.people]]
given-names = "Maximilian"
family-names = "Inckmann"
email = "maximilian.inckmann@kit.edu"
orcid = "https://orcid.org/0009-0005-2800-4833"
affiliation = "Karlsruhe Institute of Technology (KIT)"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = true  # currently maintains the project (i.e. is a contact person)

[[project.people]]
given-names = "Andreas"
family-names = "Pfeil"
email = "andreas.pfeil@kit.edu"
orcid = "https://orcid.org/0000-0001-6575-1022"
affiliation = "Karlsruhe Institute of Technology (KIT)"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = false  # currently maintains the project (i.e. is a contact person)
publication_author = true

[[project.people]]
given-names = "Thomas"
family-names = "Jejkal"
email = "thomas.jejkal@kit.edu"
orcid = "https://orcid.org/0000-0003-2804-688X"
affiliation = "Karlsruhe Institute of Technology (KIT)"
author = true      # is a full author of the project (i.e. appears in citations)
maintainer = false  # currently maintains the project (i.e. is a contact person)
publication_author = true

[config]
packages = ['packages/react-library', 'packages/stencil-library']
